"""cover

Revision ID: 346fd0b238f
Revises: 42b434e7a1e3
Create Date: 2015-09-28 00:49:40.626340

"""

# revision identifiers, used by Alembic.
revision = '346fd0b238f'
down_revision = '42b434e7a1e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('cover_url', sa.String(length=512), nullable=True))
    op.add_column('connection', sa.Column('cover_x', sa.Integer(), nullable=True))
    op.add_column('connection', sa.Column('cover_y', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'cover_y')
    op.drop_column('connection', 'cover_x')
    op.drop_column('connection', 'cover_url')
    ### end Alembic commands ###
