"""conn email

Revision ID: 42b434e7a1e3
Revises: e1855559096
Create Date: 2015-09-27 15:45:45.647993

"""

# revision identifiers, used by Alembic.
revision = '42b434e7a1e3'
down_revision = 'e1855559096'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('email', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'email')
    ### end Alembic commands ###
